### ISSUE TITLE
Is there a way to speed up the calculation of TxID, BlockHash, through SIMD?

### ISSUE THREAD

**Issue by xiuno** [rust-bitcoin/bitcoin_hashes#112]
For example, this library: https://github.com/nickbabcock/highway-rs

I found the implementation about SipHash24 in the bitcoind_hashes/src/siphash24.rs, but not found sha256.

**Comment by TheBlueMatt** [comment]
Switching hash functions isn't going to help, but copying some of the SIMD implementations out of Bitcoin Core would, indeed, speed up hashing in this crate. Doubly so for things that do many same-size hashes like merkle tree calculation.

**Comment by sgeisler** [comment]
This would most likely involve unsafe code, so it's a trade-off. Do you have a concrete need for it to be faster or was it just an observation?

**Comment by xiuno** [comment]
> This would most likely involve unsafe code, so it's a trade-off. Do you have a concrete need for it to be faster or was it just an observation?

I think official can provide unsafe implementation with feature as an option for developers.

**Comment by apoelstra** [comment]
I would really like the sha2 hashing to be faster in bitcoin_hashes. This is a significant part of our initial sync in the Liquid functionary code.

**Comment by TheBlueMatt** [comment]
It’s possible (though may not be worth the effort) that we could get some speedup with the safe SIMD primitives in std, even if not quite as much.

**Comment by elichai** [comment]
> I would really like the sha2 hashing to be faster in bitcoin_hashes. This is a significant part of our initial sync in the Liquid functionary code.

how much do we want to maintain such a thing ourselves and not use existing libraries like `sha2_asm` and friends? (we can review them if we want)

**Comment by stevenroose** [comment]
> > I would really like the sha2 hashing to be faster in bitcoin_hashes. This is a significant part of our initial sync in the Liquid functionary code.
> 
> how much do we want to maintain such a thing ourselves and not use existing libraries like `sha2_asm` and friends? (we can review them if we want)

I think if we fix their version to a fixed version that got reviewed that should be doable.

Though I think if there's any trade-off, like unsafe code or 3rd party dep, I'd prefer to have this behind a feature flag. Even though that's a bit annoying since most users get `bitcoin_hashes` through the `bitcoin` crate.

**Comment by apoelstra** [comment]
Closing in favor of https://github.com/rust-bitcoin/rust-bitcoin/issues/1424
