### ISSUE TITLE
no-std mode

### ISSUE THREAD

**Issue by sgeisler** [rust-bitcoin/bitcoin_hashes#12]
Imo the core functionality of this library could be implemented without the std lib which would enable it to be used in embedded contexts (HW wallets?). For example `byteorder` does this by having a (default) feature `std`, which can be deactivated if needed.

Am I missing something here? If not I think it's a worthwhile goal.

**Comment by apoelstra** [comment]
We depend heavily on `io::Write` and `io::Read` in our API.

**Comment by TheBlueMatt** [comment]
nostd seems like a really high bar for generic creates. Probably best to focus on building core support once rust sorts itself out.
