### ISSUE TITLE
`impl Default for sha256::Hash`  is weird

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/bitcoin_hashes#139]
I find all zeroes as the default value weird. Why it should be considered "default hash"? There's not even a known input to all zeroes hash. If there even exists something like "default hash" I'd expect it to be the hash of empty input.

This also looks like a footgun to me. We could have a constant called `ALL_ZEROES` for initialization purposes, I just wouldn't call it "default".

If there's some literature referring to all zeroes as the default hash value I'd be happy to learn but so far I didn't find anything like it.

**Comment by apoelstra** [comment]
I think we copied this from Bitcoin Core. I agree that it's weird. It was probably there to let `derive(Default)` do the "right" thing in some rust-bitcoin structures.
