### ISSUE TITLE
std::hash::Hash vs bitcoin_hashes::Hash vs bitcoin_hashes::*::Hash

### ISSUE THREAD

**Issue by dongcarl** [rust-bitcoin/bitcoin_hashes#16]
There are currently 3 different concepts all having the name `Hash`:

1. [`std::hash::Hash`](https://doc.rust-lang.org/std/hash/trait.Hash.html)
2. The trait `bitcoin_hashes::Hash`
3. The structs `bitcoin_hashes::*::Hash`

Both `bitcoin_hashes::Hash` and `std::hash::Hash` require a method named `hash`.

This also leads to some namespace conflicts that are a little confusing, see:

1. https://github.com/rust-bitcoin/bitcoin_hashes/pull/15/commits/ab648dd8eae8a83b40d3351ba8b7128c82175f5f#diff-b4aea3e418ccdb71239b96952d9cddb6R74
2. https://github.com/rust-bitcoin/bitcoin_hashes/pull/15/commits/ab648dd8eae8a83b40d3351ba8b7128c82175f5f#diff-6084d461faf67711b54610e91094c3efR101
3. https://github.com/rust-bitcoin/bitcoin_hashes/pull/15/commits/ab648dd8eae8a83b40d3351ba8b7128c82175f5f#diff-c76d1ccc0023b9b98f395f6c6da93b16R53

I propose that we rename `bitcoin_hashes::Hash` to `Digest` and for things like `bitcoin_hashes::sha256::Hash`, we rename it to `bitcoin_hashes::sha256::Sha256`.

Would like to hear what people think.

**Comment by sgeisler** [comment]
This was introduced by #11. [Relevant explanation here](https://github.com/rust-bitcoin/bitcoin_hashes/pull/11#issuecomment-445472006).

**Comment by apoelstra** [comment]
Sure we can rename `Hash` to `Digest`. I don't mind writing `sha256::Digest`.

**Comment by dongcarl** [comment]
> Sure we can rename `Hash` to `Digest`. I don't mind writing `sha256::Digest`.

Just to be clear, this would mean that the following would happen?

- `bitcoin_hashes::Hash` -> `bitcoin_hashes::Digest`
- `bitcoin_hashes::*::Hash` -> `bitcoin_hashes::*::Digest`

**Comment by apoelstra** [comment]
@dongcarl yep

**Comment by TheBlueMatt** [comment]
Can we call them something different? Like leave the Hash trait as Hash and move the implementations to Digest?

**Comment by dongcarl** [comment]
> Can we call them something different? Like leave the Hash trait as Hash and move the implementations to Digest?

The reason that I'm for changing the name of the `Hash` trait is to not conflict with `std`. I don't mind the name of the structs, you guys can decide on that.

**Comment by apoelstra** [comment]
How about renaming `Hash` trait to `Digest` and leaving the `Hash` types alone?

It's easy to avoid name conflicts with concrete types by just never importing them and using e.g. `sha256d::Hash`. With traits it's not nearly as ergonomic.

**Comment by stevenroose** [comment]
Yeah I favor using the `sha256::Hash` notation, to be honest. I'm not very opinionated on the name of the trait. I think people using the `std::hash::Hash` trait will do so in library trait implementation anyway and then the overhead of just doing `hash::Hash::hash` (with `use std::hash`) is not that big of a deal. My only concern with renaming the Hash trait is that it requires all users to change the naming. Apart from that, I think Digest is more correct anyway. We might have to rename to `DigestEngine` as well then though..

**Comment by stevenroose** [comment]
To be honest, I don't think the potential confusion is big enough to justify a breaking change of this kind (renaming the `Hash` trait).

**Comment by apoelstra** [comment]
(For my part, I recommend closing.)

**Comment by dr-orlovsky** [comment]
@tcharding there is a PR addressing this issue, but it never received considerable support: https://github.com/rust-bitcoin/bitcoin_hashes/pull/89

**Comment by tcharding** [comment]
thanks @dr-orlovsky for the link.

For what its worth, while playing around with edition 2018 I noticed that, assuming we move to edition 2018, `use Hash as HashTrait;` can be replaced with the use of `impl crate::Hash for Foo` and `use Hash as _`. So soon that part of this issue will dissolve :)

**Comment by apoelstra** [comment]
Oh, that's amazing, can you update the rust-bitcoin 2018 tracking issue with that?

**Comment by Kixunil** [comment]
I personally don't see the suggested change as very valuable. From my experience name clashes are rare in Rust, especially related to very different domains. If they happen we have good tools to resolve them. The only clash I can think of experiencing is having to write `core::fmt::Display::fmt` when forwarding `Debug`. Also "hash" seems to be more popular than "digest".

**Comment by apoelstra** [comment]
@Kixunil in my experience, when name clashes happen in Rust, they happen because of the `Hash` trait :)

**Comment by dr-orlovsky** [comment]
Shell I close with PR and the related PR #89?

**Comment by apoelstra** [comment]
I vote to close.
