### ISSUE TITLE
Hardware accelerated sha256

### ISSUE THREAD

**Issue by RCasatta** [rust-bitcoin/bitcoin_hashes#160]
In some applications sha256 is the bottleneck, it would be nice to have hardware accelerated sha256.

Would it be acceptable to optionally use via feature flag something like `sha2` crate ?

MSRV should be compatible

![Screenshot from 2022-06-06 15-02-36](https://user-images.githubusercontent.com/6470319/172190002-f9d5341b-78ad-495c-a3b4-375a1e30504a.png)

**Comment by RCasatta** [comment]
> are you hashing transaction data?

Yes, iterating blocks while keeping the UTXO set requires hashing every tx

> We're much better off going with the Bitcoin Core C

Yeah, that would be awesome but more complicated

**Comment by apoelstra** [comment]
We don't want any dependencies on RustCrypto crates. Maybe the MSRV is compatible today. It won't be tomorrow.

**Comment by apoelstra** [comment]
Closing in favor of https://github.com/rust-bitcoin/rust-bitcoin/issues/1424
