### ISSUE TITLE
`ToHex` trait is not very useful

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/bitcoin_hashes#169]
`ToHex` doesn't specify any limitations on implementation such as forbidding separators or even lower hex. Yet it seems in practice no separators and lower hex are implied.

From looking at `bitcoin` code it seems it's mainly used:

* in tests on custom types (mainly hashes) - those could have an inherent `to_hex()` method
* in serialization code on bytes - could've been free-standing `&[u8] -> String` function or `BytesExt` trait (for `T: AsRef<[u8]>`)

I didn't see any generic code use `ToHex` as a bound. And rightly so, since it can't assume anything about the output. Even if we specify the format `impl<T: LowrHex> ToHex for T` would then assume all `LowerHex` impls are correct, which is wrong and we would have to remove it or add marker `trait ToHexViaLowerHex: LowerHex {}` and then bound on it instead (This could unlock auto impls on unsized types which would be nice.) Also I didn't see `to_hex()` being called on integers which suggests it should've been implemented for `T: AsRef<[u8]>` instead, although reversed hashes probably screw it up.

I looked into separating `hex` into a full-featured custom `hex-compat` crate. The `ToHex` trait doesn't look very suitable because of these issues.

I think we should do either of these:

* Make the methods inherent and have a `BytesExt` in `bitcoin-internals` crate; each has well-specified format;
* Make the format customizable, remove impl via `LowerHex` (quite tedious, questionable value)
* Specify that `to_hex` must return lower hex without separators and add `trait ToHexViaLowerHex`
* Use `Holder` trick to select strategies via marker structs, so we can have impl via `AsRef<[u8]>` and `LowerHex` as needed

**Comment by apoelstra** [comment]
I like the first one -- make the methods inherent and have a `BytesExt`. I'd like to treat base64 the same way. (In both cases we can do small inline implementations and avoid any dependencies beyond `bitcoin-internals` itself)

**Comment by Kixunil** [comment]
I'd also like to have this on `BytesExt`: `fn fmt_hex(&self) -> FmtHex<'_>` where `FmtHex<'_>: LowerHex + UpperHex` so that allocation is not required.

**Comment by Kixunil** [comment]
After a bit of thinking, even inherent methods are not that useful for hashes. People can just call `to_string()`.
I also came up with an optimization to not make `to_string()` allocate more than once as well as decrease the cost of going through dynamic dispatch {50, 64, 128} times (for each byte twice): hand-write hex encoding into a temporary array, convert it to `str` and call single `write_str`.

If we're fine with using `unsafe` we can even call `from_utf8_unchecked()` and possibly use `MaybeUninit` to write (although the compiler will likely remove zeroing anyway).

**Comment by apoelstra** [comment]
Closing. This crate is moving to rust-bitcoin and we have a number of hex discussions over there.
