### ISSUE TITLE
hashes: Missing utility functions

### ISSUE THREAD

**Issue by dpc** [rust-bitcoin/bitcoin_hashes#45]
`as_ref()`, `as_mut()`, `to_vec()`, `as_slice()`

**Comment by stevenroose** [comment]
Do you mean for accessing the inner types?

**Comment by dpc** [comment]
Yes.

**Comment by stevenroose** [comment]
I think they are supposed to be immutable. F.e. they have `Copy`.

You have the `into_inner` method that probably is the best way to get the inner type and together with `from_inner`, it can also be mutated.

**Comment by stevenroose** [comment]
Also, they implement the various indexing traits, so you can do `&my_hash[..]` to get the underlying slice.

**Comment by dpc** [comment]
I don't understand what are you trying to say. For stuff like some generics some people might need `AsRef` one way or another. The other ones would be just convenient to have so importing `AsRef` is not neccessary. `into_inner` is nice, but what if I have `&GivenHash` for some reason?

I guess the mutability part is about not wanting the Hashes to be accidentally mutated? Fair enough.

**Comment by apoelstra** [comment]
+1 to `Deref<[u8]>` and `AsRef<[u8]>`.

I see no reason to create `to_vec` though I think we might get that for free from the above; and I don't want any mutators.

**Comment by stevenroose** [comment]
AsRef is already implemented. I implemented Deref in https://github.com/rust-bitcoin/bitcoin_hashes/pull/49.

**Comment by apoelstra** [comment]
Closed by #49
