### ISSUE TITLE
Potential license conflict

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/bitcoin_hashes#5]
The SHA2 hash algorithm largely follows the implementation in https://github.com/bitcoin-core/secp256k1/

@sipa can you please confirm that nothing in this CC0-licensed library is actually from libsecp256k1 and therefore only MIT licensed?

**Comment by TheBlueMatt** [comment]
Err, and that anything there is also released CC0/pubdom by the author(s).

**Comment by sipa** [comment]
To the extent that rewriting-a-straightforward-hashing-algorithm-using-an-implementation-in-another-language-as-template constitutes a derived work of code written by me, you have my permission to distribute it under CC0.

**Comment by apoelstra** [comment]
Thanks guys! I think that covers everything, the rest was written from spec from Wiikipedia pages.
