### ISSUE TITLE
Implement traits from `digest` crate

### ISSUE THREAD

**Issue by mkl-** [rust-bitcoin/bitcoin_hashes#60]
There is a crate `digest`. https://crates.io/crates/digest 
It contains some traits for hash functions. A lot of other crates use this interface (e.g. `hkdf`). It would be nice to have them implemented for types in `bitcoin_hashes` crate. For example implement `Digest` for `sha256::HashEngine` so it can be used in `hkdf`. 
It will require a dependency on `digest`.
I can do this if you OK with it.

**Comment by stevenroose** [comment]
If we see value in this, it should probably be an optional feature.

**Comment by apoelstra** [comment]
These traits do not compile on Rust 1.22.

**Comment by apoelstra** [comment]
We could feature-gate implementations of these traits.

**Comment by tcharding** [comment]
I was wondering if we could do this by converting our sha256 `HashEngine` into a `sha2::Sha256` hasher. This would give us a solution to this issue and also would give us access to SIMD (as discussed in #112).

I have very little knowledge around sha2 but it seems that our midstate abstraction does not map easily to the `sha2`/`digest` API. I forked `hashes` and `digest` and made a few private fields public, in particular the `sha2::ShaVarCore` struct has a `state` field that I hoped mapped to our `sha256::HashEngine`'s `h` field. However I am unable to get the following two tests to pass, the first one shows that we can convert a default engine to a `ShaVarCore` type so the data copy and endianess stuff must be all correct but the second test fails (convert after hashing some data):
```

    #[cfg(feature = "with-digest")]
    #[test]
    fn can_convert_default_to_digest_type() {
        use sha2::Digest;

        let s = "The quick brown fox jumps over the lazy dog.";

        let mut engine = sha256::HashEngine::default();
        let mut digest = engine.to_digest_type();

        engine.input(s.as_bytes());
        digest.update(s.as_bytes());

        let digest_hash = digest.finalize();
        let hash = sha256::Hash::from_engine(engine);

        assert_eq!(hash.into_inner(), digest_hash[..]);
    }

    #[cfg(feature = "with-digest")]
    #[test]
    fn can_convert_with_midstate_to_digest_type() {
        use sha2::Digest;

        let s = "The quick brown fox jumps over the lazy dog.";

        let mut engine = sha256::HashEngine::default();
        engine.input(s.as_bytes());

        let digest = engine.to_digest_type();

        let digest_hash = digest.finalize();
        let hash = sha256::Hash::from_engine(engine);

        assert_eq!(hash.into_inner(), digest_hash[..]);
    }
```

And the conversion function:
```

    #[cfg(feature = "with-digest")]
    /// Convert the engine into a type that implements the `digest` traits.
    pub fn to_digest_type(&self) -> sha2::Sha256 {
        use sha2::{Sha256, State256, Sha256VarCore};
        use digest::core_api::CtVariableCoreWrapper;

        let mut state = [0_32; 8];
        state.copy_from_slice(&self.h);

        let core = Sha256VarCore {
            state: state as State256,
            block_len: (self.length / BLOCK_SIZE) as u64,
        };
        Sha256::from_core(CtVariableCoreWrapper::from_inner(core))
    }
```

Is this worth pursuing more?

**Comment by tcharding** [comment]
My forks of `hashes` and `traits` have branches called`bitcoin_hashes` with the required changes if you want to see but they are trivial.

**Comment by apoelstra** [comment]
We should probably close this issue. Since it was opened, RustCrypto has moved beyond "does not compile with 1.22" to a clearer refusal to provide any stability guarantees. We do not want to depend on them. If we want SIMD we will need to implement it ourselves.

**Comment by apoelstra** [comment]
As far as citations, the best I can find is https://github.com/rust-bitcoin/rust-bitcoin/issues/98, which pre-dates this issue and was a (mostly) polite conversion, although they did repeatedly assert that they were willing to break MSRV in minor version bumps.

@TheBlueMatt I recall a more serious conflict with the RustCrypto team, somewhere on Github, but I can't find it. Do you recall what this was (and if it was actually serious, and was actually RustCrypto? :))

**Comment by tcharding** [comment]
I'm not arguing in favour of RustCrypto but for the record both `hashes` and `traits` repos contain in the readmes:

> MSRV bumps are considered breaking changes and will be performed only with minor version bump.

**Comment by apoelstra** [comment]
Going to close this as the repo is moving to rust-bitcoin org, and we aren't making any forward progress. It may be worth checking the RustCrypto ecosystem periodically to see if they've introduced any stability guarantees or if there's a clear path forward, since the ecosystem has matured a fair bit (and since moving our own MSRV to 1.41 we've encountered far fewer compatibility issues).
