### ISSUE TITLE
comment on HashEngine 

### ISSUE THREAD

**Issue by RCasatta** [rust-bitcoin/bitcoin_hashes#98]
https://github.com/rust-bitcoin/bitcoin_hashes/blob/6b9c472d0d2e7a109a5be02e7d2eafaaabe7d557/src/lib.rs#L66

it is not expected to implement io::Write anymore after https://github.com/rust-bitcoin/bitcoin_hashes/pull/52 ?

**Comment by apoelstra** [comment]
Yeah, I think this comment is out of date.

**Comment by stevenroose** [comment]
Addressed in https://github.com/rust-bitcoin/bitcoin_hashes/issues/98.

**Comment by RCasatta** [comment]
@stevenroose meant #96

**Comment by stevenroose** [comment]
> @stevenroose meant #96

Correct :)
